### ISSUE TITLE
C4FM Modulation in Python

### ISSUE THREAD

**Issue by JasleenKaur2308** [777arc/PySDR#18]
Hello , i'm trying to implement C4FM modulation ( input symbols -> raised cosine filter -> inverse sinc filter-> FM Modulator). What should i write in the code in python to get the desired output c4fm modulated waveform?

**Comment by 777arc** [comment]
Are you looking specifically at P25 signals?

**Comment by JasleenKaur2308** [comment]
Yes , im looking for p25 signals .

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by 777arc** [comment]
I would check out this software https://github.com/robotastic/trunk-recorder and their Discord where folks may be able to better help you out

**Comment by JasleenKaur2308** [comment]
Thank you so much for your valuable reply , but i want it in basic python and don't want it for GNU radio.

**Comment by 777arc** [comment]
If the following tx block diagram is correct (from https://www.mathworks.com/help/comm/ug/p25-spectrum-sensing-with-synthesized-and-captured-data.html) then you should be able to recover the signal with only an FM demod, because the RC filter and inverse sync filter shouldn't be 100% required, they just help shape the output.  So if you can get a recording of a high SNR P25 signal, try FM demoding it in python and plot the output to see if you see 4 distinct levels.  Make sure the signal is centered at 0 Hz before the FM demod.

![image](https://github.com/777arc/PySDR/assets/5722532/89780ab8-092c-490e-b5b9-d8b9c557c0aa)

# FM demod
df = 1.0 # normalized frequency deviation
phase = np.arctan2(np.imag(x), np.real(x)) # tan-1(Q/I)
out = np.diff(np.unwrap(phase)/(2 * np.pi * df))

**Comment by 777arc** [comment]
Feel free to reopen if you want more help
